import type { BankrollAccount, BankrollLedgerEntry } from '@miraichi/shared';
import { buildApiUrl } from '../config/client-env.js';
import type { FetchLike } from './cloud-persistence-service.js';

export interface BankrollSummary {readonly realizedBalance:number;readonly openExposure:number;readonly availableBalance:number;readonly accounts:readonly unknown[];}
export type BankrollViewState={status:'loading'}|{status:'ready';accounts:BankrollAccount[];selectedAccountId:string;ledger:BankrollLedgerEntry[];summary:BankrollSummary}|{status:'empty'}|{status:'unavailable';reason:string};
export async function loadBankrollViewState(fetcher:FetchLike=fetch,selectedAccountId?:string):Promise<BankrollViewState>{try{const response=await fetcher(buildApiUrl('/api/v1/bankroll/accounts'));if(!response.ok)return{status:'unavailable',reason:'Cloud bankroll is unavailable.'};const accounts=await response.json() as BankrollAccount[];if(!Array.isArray(accounts)||accounts.some((item)=>item.unit!=='points'))return{status:'unavailable',reason:'Cloud bankroll response is invalid.'};if(accounts.length===0)return{status:'empty'};const selected=accounts.find((item)=>item.accountId===selectedAccountId)??accounts[0]!;const [ledgerResponse,summaryResponse]=await Promise.all([fetcher(buildApiUrl(`/api/v1/bankroll/ledger?accountId=${encodeURIComponent(selected.accountId)}`)),fetcher(buildApiUrl(`/api/v1/bankroll/summary?accountId=${encodeURIComponent(selected.accountId)}`))]);if(!ledgerResponse.ok||!summaryResponse.ok)return{status:'unavailable',reason:'Cloud bankroll details are unavailable.'};const ledger=await ledgerResponse.json() as BankrollLedgerEntry[];const summary=await summaryResponse.json() as BankrollSummary;if(!Array.isArray(ledger)||typeof summary.realizedBalance!=='number'||typeof summary.openExposure!=='number'||typeof summary.availableBalance!=='number')return{status:'unavailable',reason:'Cloud bankroll response is invalid.'};return{status:'ready',accounts:structuredClone(accounts),selectedAccountId:selected.accountId,ledger:structuredClone(ledger),summary:structuredClone(summary)};}catch{return{status:'unavailable',reason:'Cloud bankroll is unavailable.'};}}
export async function createBankrollAccount(input:{accountId:string;label:string;openingBalancePoints:number},fetcher:FetchLike=fetch){const response=await fetcher(buildApiUrl('/api/v1/bankroll/accounts'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,unit:'points'})});if(!response.ok)throw new Error('Unable to create account');return response.json() as Promise<BankrollAccount>;}
export async function createLedgerEntry(input:{entryId:string;accountId:string;entryType:'deposit'|'withdrawal'|'correction';amountPoints:number;note?:string;occurredAt:string},fetcher:FetchLike=fetch){const response=await fetcher(buildApiUrl('/api/v1/bankroll/ledger'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!response.ok)throw new Error('Unable to create ledger entry');return response.json() as Promise<{account:BankrollAccount;ledgerEntry:BankrollLedgerEntry}>;}
export async function createBankrollTransfer(input:{transferId:string;fromAccountId:string;toAccountId:string;amountPoints:number;note?:string;occurredAt:string},fetcher:FetchLike=fetch){const response=await fetcher(buildApiUrl('/api/v1/bankroll/transfers'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!response.ok)throw new Error('Unable to transfer points');return response.json() as Promise<{fromAccount:BankrollAccount;toAccount:BankrollAccount;outEntry:BankrollLedgerEntry;inEntry:BankrollLedgerEntry}>;}
