import type { BankrollAccount, BankrollLedgerEntry } from '@miraichi/shared';
import { buildApiUrl } from '../config/client-env.js';
import type { FetchLike } from './cloud-persistence-service.js';

export interface BankrollSummary {readonly realizedBalance:number;readonly openExposure:number;readonly availableBalance:number;readonly accounts:readonly unknown[];}
export type BankrollViewState={status:'loading'}|{status:'ready';accounts:BankrollAccount[];selectedAccountId:string;ledger:BankrollLedgerEntry[];summary:BankrollSummary}|{status:'empty'}|{status:'compatibility';accounts:BankrollAccount[];reason:'multiple_bankroll_accounts'|'archived_bankroll_history'}|{status:'unavailable';reason:string};
export async function loadBankrollViewState(fetcher:FetchLike=fetch,_selectedAccountId?:string):Promise<BankrollViewState>{try{const response=await fetcher(buildApiUrl('/api/v1/bankroll/accounts'));if(!response.ok)return{status:'unavailable',reason:'Cloud bankroll is unavailable.'};const accounts=await response.json() as BankrollAccount[];if(!Array.isArray(accounts)||accounts.some((item)=>item.unit!=='points'))return{status:'unavailable',reason:'Cloud bankroll response is invalid.'};const active=accounts.filter((item)=>!item.archived);if(active.length===0)return accounts.length===0?{status:'empty'}:{status:'compatibility',accounts:structuredClone(accounts),reason:'archived_bankroll_history'};if(active.length>1)return{status:'compatibility',accounts:structuredClone(accounts),reason:'multiple_bankroll_accounts'};const selected=active[0]!;const [ledgerResponse,summaryResponse]=await Promise.all([fetcher(buildApiUrl(`/api/v1/bankroll/ledger?accountId=${encodeURIComponent(selected.accountId)}`)),fetcher(buildApiUrl(`/api/v1/bankroll/summary?accountId=${encodeURIComponent(selected.accountId)}`))]);if(!ledgerResponse.ok||!summaryResponse.ok)return{status:'unavailable',reason:'Cloud bankroll details are unavailable.'};const ledger=await ledgerResponse.json() as BankrollLedgerEntry[];const summary=await summaryResponse.json() as BankrollSummary;if(!Array.isArray(ledger)||typeof summary.realizedBalance!=='number'||typeof summary.openExposure!=='number'||typeof summary.availableBalance!=='number')return{status:'unavailable',reason:'Cloud bankroll response is invalid.'};return{status:'ready',accounts:structuredClone(active),selectedAccountId:selected.accountId,ledger:structuredClone(ledger),summary:structuredClone(summary)};}catch{return{status:'unavailable',reason:'Cloud bankroll is unavailable.'};}}
export async function setupBankroll(input:{openingBalancePoints:number;timeZone:string;weekStartDay:'monday'|'sunday'},fetcher:FetchLike=fetch){const response=await fetcher(buildApiUrl('/api/v1/bankroll/setup'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!response.ok)throw new Error('Unable to set up bankroll');return response.json() as Promise<{created:boolean;account:BankrollAccount}>;}
export async function createLedgerEntry(input:{entryId:string;accountId:string;entryType:'deposit'|'withdrawal'|'correction';amountPoints:number;note?:string;occurredAt:string},fetcher:FetchLike=fetch){const response=await fetcher(buildApiUrl('/api/v1/bankroll/ledger'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!response.ok)throw new Error('Unable to create ledger entry');return response.json() as Promise<{account:BankrollAccount;ledgerEntry:BankrollLedgerEntry}>;}
