import type { BankrollAccount, BankrollLedgerEntry } from '@miraichi/shared';
import type { FetchLike } from './cloud-persistence-service.js';

const getApiBaseUrl = () => (typeof window !== 'undefined' && (window as Window & { MIRAICHI_ENV?: { API_URL?: string } }).MIRAICHI_ENV?.API_URL) || '';

export type BankrollViewState={status:'loading'}|{status:'ready';accounts:BankrollAccount[];selectedAccountId:string;ledger:BankrollLedgerEntry[]}|{status:'empty'}|{status:'unavailable';reason:string};
export async function loadBankrollViewState(fetcher:FetchLike=fetch,selectedAccountId?:string):Promise<BankrollViewState>{try{const response=await fetcher(`${getApiBaseUrl()}/api/v1/bankroll/accounts`);if(!response.ok)return{status:'unavailable',reason:'Cloud bankroll is unavailable.'};const accounts=await response.json() as BankrollAccount[];if(!Array.isArray(accounts)||accounts.some((item)=>item.unit!=='points'))return{status:'unavailable',reason:'Cloud bankroll response is invalid.'};if(accounts.length===0)return{status:'empty'};const selected=accounts.find((item)=>item.accountId===selectedAccountId)??accounts[0]!;const ledgerResponse=await fetcher(`${getApiBaseUrl()}/api/v1/bankroll/ledger?accountId=${encodeURIComponent(selected.accountId)}`);if(!ledgerResponse.ok)return{status:'unavailable',reason:'Cloud bankroll ledger is unavailable.'};const ledger=await ledgerResponse.json() as BankrollLedgerEntry[];return{status:'ready',accounts:structuredClone(accounts),selectedAccountId:selected.accountId,ledger:structuredClone(ledger)};}catch{return{status:'unavailable',reason:'Cloud bankroll is unavailable.'};}}
export async function createBankrollAccount(input:{accountId:string;label:string;openingBalancePoints:number},fetcher:FetchLike=fetch){const response=await fetcher(`${getApiBaseUrl()}/api/v1/bankroll/accounts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,unit:'points'})});if(!response.ok)throw new Error('Unable to create account');return response.json() as Promise<BankrollAccount>;}
export async function createLedgerEntry(input:{entryId:string;accountId:string;entryType:BankrollLedgerEntry['entryType'];amountPoints:number;note?:string;occurredAt:string},fetcher:FetchLike=fetch){const response=await fetcher(`${getApiBaseUrl()}/api/v1/bankroll/ledger`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!response.ok)throw new Error('Unable to create ledger entry');return response.json() as Promise<{account:BankrollAccount;ledgerEntry:BankrollLedgerEntry}>;}

