import { validateCloudBetRecord, type AddBetDraft, type CloudBetRecord } from '@miraichi/shared';
import { buildApiUrl } from '../config/client-env.js';
import type { FetchLike } from './cloud-persistence-service.js';

export type BetRecordsViewState={status:'loading'}|{status:'ready';drafts:AddBetDraft[];pending:CloudBetRecord[];settled:CloudBetRecord[]}|{status:'empty'}|{status:'unavailable';reason:string};
const isDraft=(value:unknown):value is AddBetDraft=>typeof value==='object'&&value!==null&&typeof (value as AddBetDraft).draftId==='string'&&typeof (value as AddBetDraft).matchGroupId==='string';
export async function loadBetRecordsViewState(fetcher:FetchLike=fetch):Promise<BetRecordsViewState>{try{const[draftResponse,betResponse]=await Promise.all([fetcher(buildApiUrl('/api/v1/bet-drafts')),fetcher(buildApiUrl('/api/v1/bets'))]);if(!draftResponse.ok||!betResponse.ok)return{status:'unavailable',reason:'Cloud bet records are unavailable.'};const drafts=await draftResponse.json() as unknown;const bets=await betResponse.json() as unknown;if(!Array.isArray(drafts)||!drafts.every(isDraft)||!Array.isArray(bets)||!bets.every((item)=>validateCloudBetRecord(item).ok))return{status:'unavailable',reason:'Cloud bet records are invalid.'};const pending=(bets as CloudBetRecord[]).filter((item)=>item.status==='pending');const settled=(bets as CloudBetRecord[]).filter((item)=>item.status!=='pending');if(drafts.length===0&&bets.length===0)return{status:'empty'};return{status:'ready',drafts:structuredClone(drafts),pending:structuredClone(pending),settled:structuredClone(settled)};}catch{return{status:'unavailable',reason:'Cloud bet records are unavailable.'};}}
export async function saveCloudBetDraft(draft:AddBetDraft,fetcher:FetchLike=fetch):Promise<AddBetDraft>{const allowed: AddBetDraft={draftId:draft.draftId,matchGroupId:draft.matchGroupId,...(draft.homeTeamName?{homeTeamName:draft.homeTeamName}:{}),...(draft.awayTeamName?{awayTeamName:draft.awayTeamName}:{}),...(draft.selectionLabel?{selectionLabel:draft.selectionLabel}:{}),marketType:draft.marketType,...(draft.customMarketLabel?{customMarketLabel:draft.customMarketLabel}:{}),...(draft.lineValue==null?{}:{lineValue:draft.lineValue}),oddsFormat:draft.oddsFormat,oddsValue:draft.oddsValue,stakePoints:draft.stakePoints,...(draft.preBetEmotion?{preBetEmotion:draft.preBetEmotion}:{}),...(draft.preBetMotivation?{preBetMotivation:draft.preBetMotivation}:{}),...(draft.preBetNote?{preBetNote:draft.preBetNote}:{}),...(draft.notes?{notes:draft.notes}:{}),...(draft.tags?{tags:[...draft.tags]}:{}),createdAt:draft.createdAt,updatedAt:draft.updatedAt};const response=await fetcher(buildApiUrl('/api/v1/bet-drafts'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(allowed)});if(!response.ok)throw new Error('Unable to save draft');return response.json() as Promise<AddBetDraft>;}
export async function deleteCloudBetDraft(draftId:string,fetcher:FetchLike=fetch):Promise<void>{const response=await fetcher(buildApiUrl(`/api/v1/bet-drafts?id=${encodeURIComponent(draftId)}`),{method:'DELETE'});if(!response.ok)throw new Error('Unable to delete draft');}
export async function updateCloudBetDraft(draft:AddBetDraft,fetcher:FetchLike=fetch):Promise<AddBetDraft>{const response=await fetcher(buildApiUrl(`/api/v1/bet-drafts?id=${encodeURIComponent(draft.draftId)}`),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});if(!response.ok)throw new Error('Unable to update draft');return response.json() as Promise<AddBetDraft>;}
export async function patchCloudBetRecord(betId:string,patch:{status?:CloudBetRecord['status'];notes?:string;tags?:readonly string[];manualResultPoints?:number|null;settlementNote?:string},fetcher:FetchLike=fetch):Promise<CloudBetRecord>{const response=await fetcher(buildApiUrl(`/api/v1/bets?id=${encodeURIComponent(betId)}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});if(!response.ok)throw new Error('Unable to update bet record');return response.json() as Promise<CloudBetRecord>;}
