import { describe, expect, it } from 'vitest';
import { createMemoryCloudPersistenceAdapter } from '../persistence/memory-cloud-persistence-adapter.js';
import { settleBet } from './bet-settlement-service.js';

const now='2026-08-21T01:00:00.000Z';
async function setup(){const adapter=createMemoryCloudPersistenceAdapter({now:()=>now});await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});await adapter.createBetRecord({betId:'b',ownerProfileId:'owner-primary',matchGroupId:'m',bankrollAccountId:'a',homeTeamName:'Japan',awayTeamName:'Vietnam',marketType:'1X2',selectionLabel:'Japan',oddsFormat:'HK',oddsValue:0.9,stakePoints:10,status:'pending',preBetEmotion:'calm',preBetMotivation:'planned_analysis',preBetPlanAdherence:'yes',createdAt:now,updatedAt:now});return adapter;}

describe('bet settlement service',()=>{
  it('atomically settles a standard outcome using pre-bet plan adherence and is idempotent on retry',async()=>{const adapter=await setup();const command={settlementEventId:'s1',settlementType:'full_win' as const,effectiveAt:now};const first=await settleBet({adapter,ownerProfileId:'owner-primary',betId:'b',command,now});const retry=await settleBet({adapter,ownerProfileId:'owner-primary',betId:'b',command,now});expect(first).toMatchObject({event:{planAdherence:'yes'},record:{status:'settled',profitLossPoints:9},account:{currentBalancePoints:109}});expect(retry.account.currentBalancePoints).toBe(109);});
  it('appends a correction delta without rewriting pre-bet plan adherence',async()=>{const adapter=await setup();await settleBet({adapter,ownerProfileId:'owner-primary',betId:'b',command:{settlementEventId:'s1',settlementType:'full_win',effectiveAt:'2026-08-20T01:00:00.000Z'},now});const corrected=await settleBet({adapter,ownerProfileId:'owner-primary',betId:'b',command:{settlementEventId:'s2',settlementType:'full_loss',lessonNote:'Chased the result',effectiveAt:now,correctsSettlementEventId:'s1'},now:'2026-08-21T02:00:00.000Z'});expect(corrected).toMatchObject({event:{ledgerDeltaPoints:-19,effectiveAt:'2026-08-20T01:00:00.000Z',planAdherence:'yes'},record:{profitLossPoints:-10},account:{currentBalancePoints:90}});expect(await adapter.listBetSettlementEvents('owner-primary','b')).toHaveLength(2);});
  it('requires an assigned account, legacy plan adherence, and manual adjustment reason',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBetRecord({betId:'legacy',ownerProfileId:'owner-primary',matchGroupId:'m',homeTeamName:'A',awayTeamName:'B',marketType:'custom',selectionLabel:'A',oddsFormat:'HK',oddsValue:1,stakePoints:10,status:'pending',createdAt:now,updatedAt:now});await expect(settleBet({adapter,ownerProfileId:'owner-primary',betId:'legacy',command:{settlementEventId:'s',settlementType:'full_win',planAdherence:'yes',effectiveAt:now},now})).rejects.toThrow('bankroll account');await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});await adapter.updateBetRecord({...((await adapter.listBetRecords('owner-primary'))[0]!),bankrollAccountId:'a'});await expect(settleBet({adapter,ownerProfileId:'owner-primary',betId:'legacy',command:{settlementEventId:'s2',settlementType:'full_win',effectiveAt:now},now})).rejects.toThrow('plan adherence');await expect(settleBet({adapter:await setup(),ownerProfileId:'owner-primary',betId:'b',command:{settlementEventId:'s',settlementType:'manual_adjustment',profitLossPoints:2,effectiveAt:now},now})).rejects.toThrow('adjustmentReason');});
});
