import { Readable } from 'node:stream';
import { describe, expect, it } from 'vitest';
import { createMemoryCloudPersistenceAdapter } from '../persistence/memory-cloud-persistence-adapter.js';
import { handleBackups } from './backups.js';
function req(method:string,url:string,body?:unknown){const value=Readable.from(body===undefined?[]:[JSON.stringify(body)]) as Readable & {method:string;url:string};value.method=method;value.url=url;return value;}
function res(){return{statusCode:0,body:'',writeHead(code:number){this.statusCode=code;},end(body?:unknown){this.body=String(body??'');}};}
describe('backup routes',()=>{
  it('exports deterministic canonical data and logs its hash',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});const deps={adapter,ownerProfileId:'owner-primary',now:()=>new Date('2026-07-02T00:00:00.000Z')};let first=res();await handleBackups(req('POST','/api/v1/backups/export') as never,first as never,deps);let second=res();await handleBackups(req('POST','/api/v1/backups/export') as never,second as never,deps);expect(JSON.parse(first.body).schemaVersion).toBe('miraichi.cloud-backup.v1');expect(JSON.parse(first.body).sha256).toBe(JSON.parse(second.body).sha256);expect(await adapter.listBackupExports('owner-primary')).toHaveLength(1);});
  it('rejects malformed imports before writing',async()=>{const adapter=createMemoryCloudPersistenceAdapter();const out=res();await handleBackups(req('POST','/api/v1/backups/import',{schemaVersion:'bad',drafts:[{draftId:'x'}]}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);expect(await adapter.listBetDrafts('owner-primary')).toEqual([]);});
  it('returns a conflict without overwriting duplicate identities',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Existing',openingBalancePoints:100});const envelope={schemaVersion:'miraichi.cloud-backup.v1',exportedAt:'2026-07-02T00:00:00.000Z',ownerProfileId:'owner-primary',drafts:[],bets:[],bankrollAccounts:[{accountId:'a',ownerProfileId:'owner-primary',label:'Imported',unit:'points',openingBalancePoints:1,currentBalancePoints:1,archived:false,createdAt:'2026-07-02T00:00:00.000Z',updatedAt:'2026-07-02T00:00:00.000Z'}],bankrollLedgerEntries:[]};const out=res();await handleBackups(req('POST','/api/v1/backups/import',envelope) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(409);expect((await adapter.listBankrollAccounts('owner-primary'))[0]?.label).toBe('Existing');});
});
