import { Readable } from 'node:stream';
import { describe, expect, it } from 'vitest';
import { createMemoryCloudPersistenceAdapter } from '../persistence/memory-cloud-persistence-adapter.js';
import { handleBankroll } from './bankroll.js';
function req(method:string,url:string,body?:unknown){const value=Readable.from(body===undefined?[]:[JSON.stringify(body)]) as Readable & {method:string;url:string};value.method=method;value.url=url;return value;}
function res(){return{statusCode:0,body:'',writeHead(code:number){this.statusCode=code;},end(body?:unknown){this.body=String(body??'');}};}
describe('bankroll routes',()=>{
  it('creates points accounts and signed ledger entries newest-first',async()=>{const adapter=createMemoryCloudPersistenceAdapter({now:()=> '2026-07-02T00:00:00.000Z'});let out=res();await handleBankroll(req('POST','/api/v1/bankroll/accounts',{accountId:'a',label:'Main',unit:'points',openingBalancePoints:1000}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(201);out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:'e1',accountId:'a',entryType:'withdrawal',amountPoints:-100,note:'Manual',occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(JSON.parse(out.body).account.currentBalancePoints).toBe(900);expect(out.body).not.toMatch(/roi|kelly|risk|recommended/i);});
  it('rejects non-points units and zero ledger entries',async()=>{const adapter=createMemoryCloudPersistenceAdapter();let out=res();await handleBankroll(req('POST','/api/v1/bankroll/accounts',{accountId:'a',label:'Main',unit:'usd',openingBalancePoints:10}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:'e',accountId:'a',entryType:'deposit',amountPoints:0,occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);});
  it('archives accounts and rejects later ledger writes',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:10});let out=res();await handleBankroll(req('PATCH','/api/v1/bankroll/accounts?id=a',{archived:true}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(JSON.parse(out.body).archived).toBe(true);out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:'e',accountId:'a',entryType:'deposit',amountPoints:1,occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(409);});
});
