import { Readable } from 'node:stream';
import { describe, expect, it } from 'vitest';
import { createMemoryCloudPersistenceAdapter } from '../persistence/memory-cloud-persistence-adapter.js';
import { handleBankroll } from './bankroll.js';
function req(method:string,url:string,body?:unknown){const value=Readable.from(body===undefined?[]:[JSON.stringify(body)]) as Readable & {method:string;url:string};value.method=method;value.url=url;return value;}
function res(){return{statusCode:0,body:'',writeHead(code:number){this.statusCode=code;},end(body?:unknown){this.body=String(body??'');}};}
describe('bankroll routes',()=>{
  it('creates points accounts and signed ledger entries newest-first',async()=>{const adapter=createMemoryCloudPersistenceAdapter({now:()=> '2026-07-02T00:00:00.000Z'});let out=res();await handleBankroll(req('POST','/api/v1/bankroll/accounts',{accountId:'a',label:'Main',unit:'points',openingBalancePoints:1000}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(201);out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:'e1',accountId:'a',entryType:'withdrawal',amountPoints:-100,note:'Manual',occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(JSON.parse(out.body).account.currentBalancePoints).toBe(900);expect(out.body).not.toMatch(/roi|kelly|risk|recommended/i);});
  it('rejects non-points units and zero ledger entries',async()=>{const adapter=createMemoryCloudPersistenceAdapter();let out=res();await handleBankroll(req('POST','/api/v1/bankroll/accounts',{accountId:'a',label:'Main',unit:'usd',openingBalancePoints:10}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:'e',accountId:'a',entryType:'deposit',amountPoints:0,occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);});
  it('requires positive opening capital and semantic manual ledger signs',async()=>{const adapter=createMemoryCloudPersistenceAdapter();for(const openingBalancePoints of [0,-1]){const out=res();await handleBankroll(req('POST','/api/v1/bankroll/accounts',{accountId:`a-${openingBalancePoints}`,label:'Main',openingBalancePoints}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);}await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});for(const payload of [{entryId:'negative-deposit',entryType:'deposit',amountPoints:-10},{entryId:'positive-withdrawal',entryType:'withdrawal',amountPoints:10}]){const out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{...payload,accountId:'a',occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);}});
  it('rejects withdrawals and transfers that would make realized balance negative',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'A',openingBalancePoints:100});await adapter.createBankrollAccount({accountId:'b',ownerProfileId:'owner-primary',label:'B',openingBalancePoints:10});let out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:'withdraw-too-much',accountId:'a',entryType:'withdrawal',amountPoints:-101,occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(409);expect(JSON.parse(out.body).error.code).toBe('insufficient_bankroll_balance');out=res();await handleBankroll(req('POST','/api/v1/bankroll/transfers',{transferId:'too-much',fromAccountId:'a',toAccountId:'b',amountPoints:101,occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(409);expect(JSON.parse(out.body).error.code).toBe('insufficient_bankroll_balance');expect(await adapter.listBankrollAccounts('owner-primary')).toMatchObject([{accountId:'a',currentBalancePoints:100},{accountId:'b',currentBalancePoints:10}]);});
  it('archives accounts and rejects later ledger writes',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:10});let out=res();await handleBankroll(req('PATCH','/api/v1/bankroll/accounts?id=a',{archived:true}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(JSON.parse(out.body).archived).toBe(true);out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:'e',accountId:'a',entryType:'deposit',amountPoints:1,occurredAt:'2026-07-02T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(409);});
  it('reports realized, open exposure and available balance',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});await adapter.createBetRecord({betId:'b',ownerProfileId:'owner-primary',matchGroupId:'m',bankrollAccountId:'a',homeTeamName:'A',awayTeamName:'B',marketType:'1X2',selectionLabel:'A',oddsFormat:'HK',oddsValue:0.9,stakePoints:25,status:'pending',createdAt:'2026-08-21T00:00:00.000Z',updatedAt:'2026-08-21T00:00:00.000Z'});const out=res();await handleBankroll(req('GET','/api/v1/bankroll/summary') as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(JSON.parse(out.body)).toMatchObject({realizedBalance:100,openExposure:25,availableBalance:75,accounts:[{accountId:'a',openExposure:25}]});});
  it('creates linked transfers atomically',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'A',openingBalancePoints:100});await adapter.createBankrollAccount({accountId:'b',ownerProfileId:'owner-primary',label:'B',openingBalancePoints:10});const out=res();await handleBankroll(req('POST','/api/v1/bankroll/transfers',{transferId:'t',fromAccountId:'a',toAccountId:'b',amountPoints:20,occurredAt:'2026-08-21T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(201);expect(JSON.parse(out.body)).toMatchObject({fromAccount:{currentBalancePoints:80},toAccount:{currentBalancePoints:30}});});
  it('rejects one-sided transfer and settlement entries on the manual ledger endpoint', async () => {
    const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'a',ownerProfileId:'owner-primary',label:'A',openingBalancePoints:100});
    for (const entryType of ['transfer_in','transfer_out','bet_settlement']) {
      const out=res();await handleBankroll(req('POST','/api/v1/bankroll/ledger',{entryId:`e-${entryType}`,accountId:'a',entryType,amountPoints:10,occurredAt:'2026-08-21T00:00:00.000Z'}) as never,out as never,{adapter,ownerProfileId:'owner-primary'});
      expect(out.statusCode).toBe(400);
    }
  });
});
