import { Readable } from 'node:stream';
import { describe, expect, it } from 'vitest';
import { createMemoryCloudPersistenceAdapter } from '../persistence/memory-cloud-persistence-adapter.js';
import { hashBetAttemptPayload } from '../services/discipline-service.js';
import { handleBets } from './bets.js';
function request(method:string,url:string,body?:unknown){const req=Readable.from(body===undefined?[]:[JSON.stringify(body)]) as Readable & {method:string;url:string};req.method=method;req.url=url;return req;}
function response(){return{statusCode:0,body:'',writeHead(code:number){this.statusCode=code;},end(body?:unknown){this.body=String(body??'');}};}
const record={betId:'bet-1',matchGroupId:'match-1',bankrollAccountId:'account-1',homeTeamName:'Japan',awayTeamName:'Vietnam',marketType:'1X2',selectionLabel:'Japan',oddsFormat:'HK',oddsValue:0.9,stakePoints:10,preBetEmotion:'calm',preBetMotivation:'planned_analysis',createdAt:'2026-07-02T00:00:00.000Z'};
describe('bet routes',()=>{
  it('creates and patches owner records',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'account-1',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});let res=response();await handleBets(request('POST','/api/v1/bets',record) as never,res as never,{adapter,ownerProfileId:'owner-primary',now:()=>new Date('2026-07-02T00:00:00.000Z')});expect(res.statusCode).toBe(201);expect(JSON.parse(res.body)).toMatchObject({status:'pending',bankrollAccountId:'account-1'});res=response();await handleBets(request('PATCH','/api/v1/bets?id=bet-1',{notes:'edited'}) as never,res as never,{adapter,ownerProfileId:'owner-primary'});expect(JSON.parse(res.body).notes).toBe('edited');});
  it('keeps settlement projections behind the settlement endpoint',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'account-1',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});await adapter.createBetRecord({...record,marketType:'1X2' as const,oddsFormat:'HK' as const,preBetEmotion:'calm' as const,preBetMotivation:'planned_analysis' as const,ownerProfileId:'owner-primary',status:'pending',updatedAt:record.createdAt});for(const patch of [{status:'settled'},{manualResultPoints:9},{settlementNote:'bypass'}]){const out=response();await handleBets(request('PATCH','/api/v1/bets?id=bet-1',patch) as never,out as never,{adapter,ownerProfileId:'owner-primary'});expect(out.statusCode).toBe(400);expect(JSON.parse(out.body).error.code).toBe('invalid_cloud_record');}expect(await adapter.listBetRecords('owner-primary')).toMatchObject([{status:'pending'}]);expect(await adapter.listBankrollLedgerEntries('owner-primary','account-1')).toEqual([]);});
  it('rejects formula and AI fields',async()=>{const res=response();await handleBets(request('POST','/api/v1/bets',{...record,roi:10,recommendedStake:20}) as never,res as never,{adapter:createMemoryCloudPersistenceAdapter(),ownerProfileId:'owner-primary'});expect(res.statusCode).toBe(400);expect(JSON.parse(res.body).error.code).toBe('invalid_cloud_record');});
  it('returns 404 for an unknown patch target',async()=>{const res=response();await handleBets(request('PATCH','/api/v1/bets?id=missing',{notes:'missing'}) as never,res as never,{adapter:createMemoryCloudPersistenceAdapter(),ownerProfileId:'owner-primary'});expect(res.statusCode).toBe(404);});
  it('requires and consumes a completed challenge when a rule is triggered',async()=>{const adapter=createMemoryCloudPersistenceAdapter();await adapter.createBankrollAccount({accountId:'account-1',ownerProfileId:'owner-primary',label:'Main',openingBalancePoints:100});await adapter.upsertDisciplineConfig({ownerProfileId:'owner-primary',dailyStopLossPoints:null,weeklyStopLossPoints:null,bigBetThresholdPoints:10,timeZone:'Asia/Tokyo',cooldownSeconds:15,version:1,updatedAt:'2026-07-02T00:00:00.000Z'});let out=response();await handleBets(request('POST','/api/v1/bets',record) as never,out as never,{adapter,ownerProfileId:'owner-primary',now:()=>new Date('2026-07-02T00:00:00.000Z')});expect(out.statusCode).toBe(409);expect(JSON.parse(out.body).error.code).toBe('discipline_ack_required');await adapter.createDisciplineChallenge({challengeId:'c',ownerProfileId:'owner-primary',payloadHash:hashBetAttemptPayload(record),ruleVersion:1,triggeredRules:['big_bet'],dailyProfitLossPoints:0,weeklyProfitLossPoints:0,createdAt:'2026-07-02T00:00:00.000Z',availableAt:'2026-07-02T00:00:15.000Z'});out=response();await handleBets(request('POST','/api/v1/bets',{...record,disciplineChallengeId:'c'}) as never,out as never,{adapter,ownerProfileId:'owner-primary',now:()=>new Date('2026-07-02T00:00:15.000Z')});expect(out.statusCode).toBe(201);expect(JSON.parse(out.body).disciplineSnapshot).toMatchObject({triggeredRules:['big_bet']});});
});
