import type {
  AddBetDraft, BackupExportReceipt, BankrollAccount, BankrollLedgerEntry, CloudBackupEnvelope,
  CloudBetRecord, CloudMatchSnapshot, CreateBankrollAccountInput, CreateBankrollLedgerEntryInput,
  LocalDataSnapshotStatus, LocalMatch, LocalMatchFeedResponse, LocalMatchSnapshotQuery,
  UpdateBankrollAccountInput
} from '@miraichi/shared/src/contracts/index.js';
import type { CloudPersistenceAdapter } from '../cloud-persistence-adapter.js';
import type { PostgresQueryClient } from './postgres-query-client.js';

type Row = Record<string, unknown>;
export interface SupabaseCloudPersistenceOptions { client: PostgresQueryClient; ownerProfileId: string; now?: () => string }
const clone = <T>(value: T): T => structuredClone(value);
const number = (value: unknown) => typeof value === 'number' ? value : Number(value);
const text = (value: unknown) => String(value ?? '');
const optionalText = (value: unknown) => value == null ? undefined : String(value);
const dateText = (value: unknown) => value instanceof Date ? value.toISOString() : text(value);

function mapDraft(row: Row): AddBetDraft {
  return {
    draftId: text(row.draft_id), matchGroupId: text(row.match_group_id), marketType: text(row.market_type) as AddBetDraft['marketType'],
    ...(row.custom_market_label == null ? {} : { customMarketLabel: text(row.custom_market_label) }),
    ...(row.line_value == null ? {} : { lineValue: number(row.line_value) }), oddsFormat: 'HK', oddsValue: number(row.odds_value),
    stakePoints: number(row.stake_points), ...(row.notes == null ? {} : { notes: text(row.notes) }),
    tags: Array.isArray(row.tags) ? row.tags.map(String) : [], createdAt: dateText(row.created_at), updatedAt: dateText(row.updated_at)
  };
}
function mapBet(row: Row): CloudBetRecord {
  return {
    betId: text(row.bet_id), ownerProfileId: text(row.owner_profile_id), matchGroupId: text(row.match_group_id),
    ...(row.match_id == null ? {} : { matchId: text(row.match_id) }), homeTeamName: text(row.home_team_name), awayTeamName: text(row.away_team_name),
    ...(row.competition_label == null ? {} : { competitionLabel: text(row.competition_label) }), ...(row.season_label == null ? {} : { seasonLabel: text(row.season_label) }),
    marketType: text(row.market_type) as CloudBetRecord['marketType'], ...(row.custom_market_label == null ? {} : { customMarketLabel: text(row.custom_market_label) }),
    selectionLabel: text(row.selection_label), ...(row.line_value == null ? {} : { lineValue: number(row.line_value) }), oddsFormat: 'HK', oddsValue: number(row.odds_value),
    stakePoints: number(row.stake_points), status: text(row.status) as CloudBetRecord['status'],
    ...(row.settlement_note == null ? {} : { settlementNote: text(row.settlement_note) }), ...(row.manual_result_points == null ? {} : { manualResultPoints: number(row.manual_result_points) }),
    ...(row.notes == null ? {} : { notes: text(row.notes) }), tags: Array.isArray(row.tags) ? row.tags.map(String) : [],
    createdAt: dateText(row.created_at), updatedAt: dateText(row.updated_at)
  };
}
function mapAccount(row: Row): BankrollAccount {
  return { accountId: text(row.account_id), ownerProfileId: text(row.owner_profile_id), label: text(row.label), unit: 'points', openingBalancePoints: number(row.opening_balance_points), currentBalancePoints: number(row.current_balance_points), archived: Boolean(row.archived), createdAt: dateText(row.created_at), updatedAt: dateText(row.updated_at) };
}
function mapLedger(row: Row): BankrollLedgerEntry {
  return { entryId: text(row.entry_id), ownerProfileId: text(row.owner_profile_id), accountId: text(row.account_id), entryType: text(row.entry_type) as BankrollLedgerEntry['entryType'], amountPoints: number(row.amount_points), ...(row.note == null ? {} : { note: text(row.note) }), occurredAt: dateText(row.occurred_at), createdAt: dateText(row.created_at) };
}
function mapMatch(row: Row): LocalMatch {
  return { id: text(row.id), competition: { id: text(row.competition_id), name: text(row.competition_name), type: 'national-team', season: text(row.season) }, kickoffUtc: dateText(row.kickoff_utc), status: text(row.status) as LocalMatch['status'], homeTeam: { id: text(row.home_team_id), name: text(row.home_team_name), ...(row.home_country_code == null ? {} : { countryCode: text(row.home_country_code) }) }, awayTeam: { id: text(row.away_team_id), name: text(row.away_team_name), ...(row.away_country_code == null ? {} : { countryCode: text(row.away_country_code) }) }, score: { home: row.home_score == null ? null : number(row.home_score), away: row.away_score == null ? null : number(row.away_score) }, ...(row.venue == null ? {} : { venue: text(row.venue) }), ...(row.round_label == null ? {} : { round: text(row.round_label) }), ...(row.stage == null ? {} : { stage: text(row.stage) }), ...(row.neutral_venue == null ? {} : { neutralVenue: Boolean(row.neutral_venue) }), sourceRefs: Array.isArray(row.source_refs) ? row.source_refs as LocalMatch['sourceRefs'] : [], updatedAt: dateText(row.updated_at) };
}

export function createSupabaseCloudPersistenceAdapter(options: SupabaseCloudPersistenceOptions): CloudPersistenceAdapter {
  const { client, ownerProfileId } = options; const now = options.now ?? (() => new Date().toISOString());
  const assertOwner = (owner: string) => { if (owner !== ownerProfileId) throw new Error('Owner profile mismatch'); };
  const status = async (): Promise<LocalDataSnapshotStatus> => {
    const snapshot = await client.query<Row>('select snapshot_id, generated_at, imported_at, sources from miraichi_app.match_snapshot where owner_profile_id = $1 order by imported_at desc limit 1', [ownerProfileId]);
    if (!snapshot.rows[0]) return { snapshotId: 'cloud-missing', generatedAt: now(), importedAt: now(), matchCount: 0, competitions: [], sources: [], freshness: 'missing', warnings: ['Cloud match snapshot is unavailable.'] };
    const counts = await client.query<Row>('select competition_id as id, competition_name as name, array_agg(distinct season) as seasons, count(*)::int as match_count from miraichi_app.match_record where owner_profile_id = $1 and snapshot_id = $2 group by competition_id, competition_name', [ownerProfileId, snapshot.rows[0].snapshot_id]);
    return { snapshotId: text(snapshot.rows[0].snapshot_id), generatedAt: dateText(snapshot.rows[0].generated_at), importedAt: dateText(snapshot.rows[0].imported_at), matchCount: counts.rows.reduce((sum, row) => sum + number(row.match_count), 0), competitions: counts.rows.map((row) => ({ id: text(row.id), name: text(row.name), seasons: Array.isArray(row.seasons) ? row.seasons.map(String) : [], matchCount: number(row.match_count) })), sources: Array.isArray(snapshot.rows[0].sources) ? snapshot.rows[0].sources as LocalDataSnapshotStatus['sources'] : [], freshness: 'fresh', warnings: [] };
  };
  return {
    getStatus: async () => { try { await client.query('select 1 as ok'); return { provider: 'supabase-postgres', mode: 'supabase', state: 'ready', checkedAt: now() }; } catch { return { provider: 'supabase-postgres', mode: 'supabase', state: 'unavailable', checkedAt: now(), message: 'Cloud database is unavailable.' }; } },
    saveBetDraft: async (owner, draft) => { assertOwner(owner); const result = await client.query<Row>(`with owner_row as (insert into miraichi_app.app_profile (id,label) values ($1,$1) on conflict (id) do nothing) insert into miraichi_app.bet_draft (draft_id,owner_profile_id,match_group_id,market_type,custom_market_label,line_value,odds_format,odds_value,stake_points,notes,tags,created_at,updated_at) values ($2,$1,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) on conflict (owner_profile_id,draft_id) do update set match_group_id=excluded.match_group_id,market_type=excluded.market_type,custom_market_label=excluded.custom_market_label,line_value=excluded.line_value,odds_value=excluded.odds_value,stake_points=excluded.stake_points,notes=excluded.notes,tags=excluded.tags,updated_at=excluded.updated_at returning *`, [owner,draft.draftId,draft.matchGroupId,draft.marketType,draft.customMarketLabel ?? null,draft.lineValue ?? null,draft.oddsFormat,draft.oddsValue,draft.stakePoints,draft.notes ?? null,draft.tags ?? [],draft.createdAt,draft.updatedAt]); return result.rows[0] ? mapDraft(result.rows[0]) : clone(draft); },
    listBetDrafts: async (owner) => { assertOwner(owner); const result = await client.query<Row>('select * from miraichi_app.bet_draft where owner_profile_id = $1 order by updated_at desc', [owner]); return result.rows.map(mapDraft); },
    deleteBetDraft: async (owner,id) => { assertOwner(owner); return (await client.query('delete from miraichi_app.bet_draft where owner_profile_id = $1 and draft_id = $2',[owner,id])).rowCount > 0; },
    createBetRecord: async (record) => { assertOwner(record.ownerProfileId); const result = await client.query<Row>(`with owner_row as (insert into miraichi_app.app_profile (id,label) values ($1,$1) on conflict (id) do nothing) insert into miraichi_app.bet_record (bet_id,owner_profile_id,match_group_id,match_id,home_team_name,away_team_name,competition_label,season_label,market_type,custom_market_label,selection_label,line_value,odds_format,odds_value,stake_points,status,settlement_note,manual_result_points,notes,tags,created_at,updated_at) values ($2,$1,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22) returning *`, [record.ownerProfileId,record.betId,record.matchGroupId,record.matchId ?? null,record.homeTeamName,record.awayTeamName,record.competitionLabel ?? null,record.seasonLabel ?? null,record.marketType,record.customMarketLabel ?? null,record.selectionLabel,record.lineValue ?? null,record.oddsFormat,record.oddsValue,record.stakePoints,record.status,record.settlementNote ?? null,record.manualResultPoints ?? null,record.notes ?? null,record.tags ?? [],record.createdAt,record.updatedAt]); return result.rows[0] ? mapBet(result.rows[0]) : clone(record); },
    listBetRecords: async (owner) => { assertOwner(owner); return (await client.query<Row>('select * from miraichi_app.bet_record where owner_profile_id = $1 order by updated_at desc',[owner])).rows.map(mapBet); },
    updateBetRecord: async (record) => { assertOwner(record.ownerProfileId); const result = await client.query<Row>('update miraichi_app.bet_record set status=$3,settlement_note=$4,manual_result_points=$5,notes=$6,tags=$7,updated_at=$8 where owner_profile_id=$1 and bet_id=$2 returning *',[record.ownerProfileId,record.betId,record.status,record.settlementNote ?? null,record.manualResultPoints ?? null,record.notes ?? null,record.tags ?? [],record.updatedAt]); if (!result.rows[0]) throw new Error('Bet record not found'); return mapBet(result.rows[0]); },
    createBankrollAccount: async (input: CreateBankrollAccountInput) => { assertOwner(input.ownerProfileId); const created=now(); const result=await client.query<Row>(`with owner_row as (insert into miraichi_app.app_profile (id,label) values ($1,$1) on conflict (id) do nothing) insert into miraichi_app.bankroll_account (account_id,owner_profile_id,label,unit,opening_balance_points,current_balance_points,archived,created_at,updated_at) values ($2,$1,$3,'points',$4,$4,false,$5,$5) returning *`,[input.ownerProfileId,input.accountId,input.label,input.openingBalancePoints,created]); return result.rows[0] ? mapAccount(result.rows[0]) : { ...input, unit:'points',currentBalancePoints:input.openingBalancePoints,archived:false,createdAt:created,updatedAt:created }; },
    listBankrollAccounts: async (owner) => { assertOwner(owner); return (await client.query<Row>('select * from miraichi_app.bankroll_account where owner_profile_id=$1 order by created_at',[owner])).rows.map(mapAccount); },
    updateBankrollAccount: async (input: UpdateBankrollAccountInput) => { assertOwner(input.ownerProfileId); const result=await client.query<Row>('update miraichi_app.bankroll_account set label=coalesce($3,label),archived=coalesce($4,archived),updated_at=$5 where owner_profile_id=$1 and account_id=$2 returning *',[input.ownerProfileId,input.accountId,input.label ?? null,input.archived ?? null,now()]); if(!result.rows[0]) throw new Error('Bankroll account not found'); return mapAccount(result.rows[0]); },
    createBankrollLedgerEntry: async (input: CreateBankrollLedgerEntryInput) => { assertOwner(input.ownerProfileId); const created=now(); return client.transaction(async (tx) => { const inserted=await tx.query<Row>('insert into miraichi_app.bankroll_ledger_entry (entry_id,owner_profile_id,account_id,entry_type,amount_points,note,occurred_at,created_at) values ($1,$2,$3,$4,$5,$6,$7,$8) returning *',[input.entryId,input.ownerProfileId,input.accountId,input.entryType,input.amountPoints,input.note ?? null,input.occurredAt,created]); const updated=await tx.query<Row>('update miraichi_app.bankroll_account set current_balance_points=current_balance_points+$3,updated_at=$4 where owner_profile_id=$1 and account_id=$2 and archived=false returning account_id',[input.ownerProfileId,input.accountId,input.amountPoints,created]); if(!updated.rowCount) throw new Error('Bankroll account not found or archived'); return inserted.rows[0] ? mapLedger(inserted.rows[0]) : { ...input, createdAt:created }; }); },
    listBankrollLedgerEntries: async (owner,accountId) => { assertOwner(owner); return (await client.query<Row>('select * from miraichi_app.bankroll_ledger_entry where owner_profile_id=$1 and account_id=$2 order by occurred_at desc',[owner,accountId])).rows.map(mapLedger); },
    upsertMatchSnapshot: async (owner,snapshot: CloudMatchSnapshot) => { assertOwner(owner); await client.transaction(async (tx) => { await tx.query(`with owner_row as (insert into miraichi_app.app_profile (id,label) values ($1,$1) on conflict (id) do nothing) insert into miraichi_app.match_snapshot (snapshot_id,owner_profile_id,generated_at,imported_at,sources) values ($2,$1,$3,$4,$5) on conflict (snapshot_id) do update set generated_at=excluded.generated_at,imported_at=excluded.imported_at,sources=excluded.sources`,[owner,snapshot.snapshotId,snapshot.generatedAt,snapshot.importedAt,snapshot.sources]); for(const match of snapshot.matches) await tx.query(`insert into miraichi_app.match_record (id,owner_profile_id,snapshot_id,competition_id,competition_name,competition_type,season,kickoff_utc,status,home_team_id,home_team_name,home_country_code,away_team_id,away_team_name,away_country_code,home_score,away_score,venue,round_label,stage,neutral_venue,source_refs,updated_at) values ($1,$2,$3,$4,$5,'national-team',$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22) on conflict (id) do update set snapshot_id=excluded.snapshot_id,status=excluded.status,home_score=excluded.home_score,away_score=excluded.away_score,source_refs=excluded.source_refs,updated_at=excluded.updated_at`,[match.id,owner,snapshot.snapshotId,match.competition.id,match.competition.name,match.competition.season,match.kickoffUtc,match.status,match.homeTeam.id,match.homeTeam.name,match.homeTeam.countryCode ?? null,match.awayTeam.id,match.awayTeam.name,match.awayTeam.countryCode ?? null,match.score.home,match.score.away,match.venue ?? null,match.round ?? null,match.stage ?? null,match.neutralVenue ?? null,match.sourceRefs,match.updatedAt]); }); },
    listCloudMatches: async (owner,query: LocalMatchSnapshotQuery): Promise<LocalMatchFeedResponse> => { assertOwner(owner); const values: unknown[]=[owner]; const where=['owner_profile_id=$1']; if(query.date){values.push(query.date);where.push(`kickoff_utc::date=$${values.length}::date`);} if(query.competitionId){values.push(query.competitionId);where.push(`competition_id=$${values.length}`);} if(query.status){values.push(query.status);where.push(`status=$${values.length}`);} const rows=await client.query<Row>(`select * from miraichi_app.match_record where ${where.join(' and ')} order by kickoff_utc`,values); return {matches:rows.rows.map(mapMatch),snapshot:await status()}; },
    findCloudMatchById: async (owner,id) => { assertOwner(owner); const row=(await client.query<Row>('select * from miraichi_app.match_record where owner_profile_id=$1 and id=$2',[owner,id])).rows[0]; return row ? mapMatch(row) : null; },
    getCloudMatchSnapshotStatus: async (owner) => { assertOwner(owner); return status(); },
    exportOwnerData: async (owner,exportedAt): Promise<CloudBackupEnvelope> => { assertOwner(owner); return {schemaVersion:'miraichi.cloud-backup.v1',exportedAt,ownerProfileId:owner,drafts:[...(await client.query<Row>('select * from miraichi_app.bet_draft where owner_profile_id=$1 order by draft_id',[owner])).rows.map(mapDraft)],bets:[...(await client.query<Row>('select * from miraichi_app.bet_record where owner_profile_id=$1 order by bet_id',[owner])).rows.map(mapBet)],bankrollAccounts:[...(await client.query<Row>('select * from miraichi_app.bankroll_account where owner_profile_id=$1 order by account_id',[owner])).rows.map(mapAccount)],bankrollLedgerEntries:[...(await client.query<Row>('select * from miraichi_app.bankroll_ledger_entry where owner_profile_id=$1 order by entry_id',[owner])).rows.map(mapLedger)]}; },
    importOwnerData: async (owner,envelope) => { assertOwner(owner); if(envelope.ownerProfileId!==owner) throw new Error('Backup owner mismatch'); await client.transaction(async (tx)=>{ for(const draft of envelope.drafts) await tx.query('insert into miraichi_app.bet_draft (draft_id,owner_profile_id,match_group_id,market_type,odds_format,odds_value,stake_points,created_at,updated_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[draft.draftId,owner,draft.matchGroupId,draft.marketType,draft.oddsFormat,draft.oddsValue,draft.stakePoints,draft.createdAt,draft.updatedAt]); for(const bet of envelope.bets) await tx.query('insert into miraichi_app.bet_record (bet_id,owner_profile_id,match_group_id,home_team_name,away_team_name,market_type,selection_label,odds_format,odds_value,stake_points,status,created_at,updated_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[bet.betId,owner,bet.matchGroupId,bet.homeTeamName,bet.awayTeamName,bet.marketType,bet.selectionLabel,bet.oddsFormat,bet.oddsValue,bet.stakePoints,bet.status,bet.createdAt,bet.updatedAt]); for(const account of envelope.bankrollAccounts) await tx.query('insert into miraichi_app.bankroll_account (account_id,owner_profile_id,label,unit,opening_balance_points,current_balance_points,archived,created_at,updated_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[account.accountId,owner,account.label,account.unit,account.openingBalancePoints,account.currentBalancePoints,account.archived,account.createdAt,account.updatedAt]); for(const entry of envelope.bankrollLedgerEntries) await tx.query('insert into miraichi_app.bankroll_ledger_entry (entry_id,owner_profile_id,account_id,entry_type,amount_points,note,occurred_at,created_at) values ($1,$2,$3,$4,$5,$6,$7,$8)',[entry.entryId,owner,entry.accountId,entry.entryType,entry.amountPoints,entry.note ?? null,entry.occurredAt,entry.createdAt]); }); },
    recordBackupExport: async (receipt) => { assertOwner(receipt.ownerProfileId); await client.query('insert into miraichi_app.backup_export_log (export_id,owner_profile_id,schema_version,exported_at,sha256,record_counts) values ($1,$2,$3,$4,$5,$6)',[receipt.exportId,receipt.ownerProfileId,receipt.schemaVersion,receipt.exportedAt,receipt.sha256,receipt.recordCounts]); },
    listBackupExports: async (owner) => { assertOwner(owner); const result=await client.query<Row>('select * from miraichi_app.backup_export_log where owner_profile_id=$1 order by exported_at desc',[owner]); return result.rows.map((row)=>({exportId:text(row.export_id),ownerProfileId:text(row.owner_profile_id),schemaVersion:'miraichi.cloud-backup.v1',exportedAt:dateText(row.exported_at),sha256:text(row.sha256),recordCounts:row.record_counts as BackupExportReceipt['recordCounts']})); }
  };
}
